version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: HoneybeeSchema
    versions:
    - 1.42.2.2
    - 1.43.0
    - 1.43.0.1
  commit-message:
    prefix: fix
    include: scope
